apiVersion: v1
kind: Service
metadata:
  name: mlflow-postgresql-svc
  namespace: mlflow
  labels:
    mlflow: mlflow-service
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
  selector:
    app: mlflow-postgresql