apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-tracking-server
  namespace: mlflow
  labels:
      app: mlflow-tracking-server
spec:
  # The replica count is kept to one for simplicity purposes.
  # To create a highly available app, the replica count would
  # be higher.
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-tracking-server-pods
  template:
    metadata:
      labels:
        app: mlflow-tracking-server-pods
    spec:
    ##  The init container is needed only if we update the version of mlflow to do DB migration
      initContainers:
      - name: database-upgrade
        image: ghcr.io/dkr290/mlflow-cicd:${COMMIT}
        command: ['sh', '-c','mlflow db upgrade  postgresql://$DB_USERNAME:$DB_PASSWORD@$DB_URL/$DB_NAME' ]
        env: # we extract the values we set in the configmap and mount them as environmen variables in the pods.
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: DB_PASSWORD
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_USERNAME
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_NAME
      containers:
        - name: mlflow-tracking-server-pod
          # The docker image is pulled from dockerhub.
          image: ghcr.io/dkr290/mlflow-cicd:${COMMIT}
          imagePullPolicy: Always
          env: # we extract the values we set in the configmap and mount them as environmen variables in the pods.
          - name: DEFAULT_ARTIFACT_ROOT
            valueFrom:
              configMapKeyRef:
                name: default-artifact-root
                key: DEFAULT_ARTIFACT_ROOT
           
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mlflow-secret
                key: DB_PASSWORD
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_USERNAME
          - name: DB_URL
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: mlflow-configmap
                key: DB_NAME
          
          
          resources:
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: 256Mi
              cpu: "0.3"
      imagePullSecrets:
      - name: ghcr-cred
    

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlflow-tracking-server
  name: mlflow-tracking-server
  namespace: mlflow
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlflow-tracking-server-pods