name: mlflow-build-deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  #  paths-ignore:
  #    - '.github/**'
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  mlflow-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MLFLOW_DOCKER_IMAGE: danikr238/mlflow2.0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: docker version and build
        run: |
            docker -v
            docker build . -t $MLFLOW_DOCKER_IMAGE:$GITHUB_RUN_ID
            docker images -a
      - name: docker login and push
        run: | 
         docker login -u ${{ secrets.dockerhubusername }} -p ${{ secrets.dockerhubpassword }}
         docker push $MLFLOW_DOCKER_IMAGE:$GITHUB_RUN_ID
  mlflow-deploy-aks:
    needs: mlflow-build
    runs-on: ubuntu-latest

    - name: Get K8s context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: aks-rg-dev
          cluster-name: aks-cluster-dev
        id: login  
      